[tox]
env_list = ruff, mypy, pylint, py{311,312,313,314}

[testenv]
dependency_groups = dev
commands = pytest {posargs}

[testenv:ruff]
dependency_groups = dev
commands =
    ruff check src tests
    ruff format --check src tests

[testenv:mypy]
dependency_groups = dev
commands = mypy src

[testenv:pylint]
dependency_groups = dev
commands = pylint src
